<body>
<style/>

<h1>Story wall</h1>

<div class="wall-column">
    <h2 class="column-title">Backlog</h2>
    <ul id="backlog" class="column-data">
    </ul>
</div>

<div class="wall-column">
    <h2 class="column-title">In Progress</h2>
    <ul id="inProgress" class="column-data">
    </ul>
</div>

<div class="wall-column">
    <h2 class="column-title">Done</h2>
    <ul id="done" class="column-data">
    </ul>
</div>


</body>
